// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory(arg1) {
  return window['go']['main']['App']['ClearHistory'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function GetColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetColumns'](arg1, arg2, arg3);
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetSchemas(arg1) {
  return window['go']['main']['App']['GetSchemas'](arg1);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function LockWrites(arg1) {
  return window['go']['main']['App']['LockWrites'](arg1);
}

export function LogFrontendEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogFrontendEvent'](arg1, arg2, arg3);
}

export function ReadTable(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ReadTable'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RunQuery(arg1, arg2) {
  return window['go']['main']['App']['RunQuery'](arg1, arg2);
}

export function SaveConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConnection'](arg1, arg2, arg3);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function UnlockWrites(arg1) {
  return window['go']['main']['App']['UnlockWrites'](arg1);
}

export function WritesUnlocked(arg1) {
  return window['go']['main']['App']['WritesUnlocked'](arg1);
}
