// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {introspect} from '../models';
import {history} from '../models';
import {config} from '../models';
import {query} from '../models';

export function ClearHistory(arg1:string):Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function GetColumns(arg1:string,arg2:string,arg3:string):Promise<Array<introspect.ColumnInfo>>;

export function GetHistory(arg1:string):Promise<Array<history.Entry>>;

export function GetSchemas(arg1:string):Promise<Array<string>>;

export function GetTables(arg1:string,arg2:string):Promise<Array<introspect.TableInfo>>;

export function ListConnections():Promise<Array<config.Connection>>;

export function LockWrites(arg1:string):Promise<void>;

export function LogFrontendEvent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReadTable(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:query.SortSpec):Promise<query.QueryResult>;

export function RunQuery(arg1:string,arg2:string):Promise<query.QueryResult>;

export function SaveConnection(arg1:config.Connection,arg2:string,arg3:boolean):Promise<void>;

export function TestConnection(arg1:config.Connection,arg2:string):Promise<void>;

export function UnlockWrites(arg1:string):Promise<void>;

export function WritesUnlocked(arg1:string):Promise<boolean>;
